### ISSUE TITLE
Deploying to Heroku requires case sensitive require reference

### ISSUE THREAD

**Issue by dgbittner** [spencermountain/wtf_wikipedia#107]
Hi there,

Love this package.

I updated to the latest version (4.0) and found my application no longer works after deploying to Heroku.

I believe it is because the require statements are case sensitive.

module.js:471
2018-05-29T13:57:57.799451+00:00 app[web.1]: throw err;
2018-05-29T13:57:57.799453+00:00 app[web.1]: ^
2018-05-29T13:57:57.799454+00:00 app[web.1]:
2018-05-29T13:57:57.799456+00:00 app[web.1]: Error: Cannot find module './KeyValue'
2018-05-29T13:57:57.799458+00:00 app[web.1]: at Function.Module._resolveFilename (module.js:469:15)
2018-05-29T13:57:57.799460+00:00 app[web.1]: at Function.Module._load (module.js:417:25)
2018-05-29T13:57:57.799461+00:00 app[web.1]: at Module.require (module.js:497:17)
2018-05-29T13:57:57.799463+00:00 app[web.1]: at require (internal/module.js:20:19)
2018-05-29T13:57:57.799464+00:00 app[web.1]: at Object.<anonymous> (/app/node_modules/wtf_wikipedia/src/templates/generic/index.js:3:20)
2018-05-29T13:57:57.799466+00:00 app[web.1]: at Module._compile (module.js:570:32)
2018-05-29T13:57:57.799467+00:00 app[web.1]: at Object.Module._extensions..js (module.js:579:10)
2018-05-29T13:57:57.799469+00:00 app[web.1]: at Module.load (module.js:487:32)
2018-05-29T13:57:57.799470+00:00 app[web.1]: at tryModuleLoad (module.js:446:12)
2018-05-29T13:57:57.799472+00:00 app[web.1]: at Function.Module._load (module.js:438:3)

Noting that in:
wtf_wikipedia/src/templates/generic/index.js

const doKeyValue = require('./KeyValue');

should be:

const doKeyValue = require('./keyValue');

Could you make this change - keen to use the new features you have added.

Thanks!

**Comment by spencermountain** [comment]
oh hey! good find.
sorry bout that.
will fix it today

**Comment by spencermountain** [comment]
hey, fixed in 4.0.1

**Comment by dgbittner** [comment]
Thanks mate! Will check it out today.
