### ISSUE TITLE
cannot read property '0' of undefined

### ISSUE THREAD

**Issue by simra** [spencermountain/wtf_wikipedia#111]
Hi, thanks for the great library.
I'm having issues with an ungraceful exit from postProcess. It looks like the fetched result is empty and postProcess chokes. I'm troubleshooting why the result is empty, but in the meantime it would be good to trap this condition.
```
unhandledRejection TypeError: Cannot read property '0' of undefined
    at pages.map.id (c:\data_rsim\xdevice\wikipedia\node_modules\wtf_wikipedia\src\fetch.js:37:30)
    at Array.map (native)
    at postProcess (c:\data_rsim\xdevice\wikipedia\node_modules\wtf_wikipedia\src\fetch.js:35:20)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Loosely related: for some reason .catch() didn't work and I had to use a global handler. Is there a better way than this?
```
process.on('unhandledRejection', error => {
    // Prints "unhandledRejection woops!"
    console.log('unhandledRejection', error);
  });
```

**Comment by simra** [comment]
It turns out the issue is that in error cases the API returns an object indexed at -1, and fetch.js throws an error attempting to process it here:
```
let page = data.query.pages[id] || {};
let text = page.revisions[0]['*'];
```
The page has no member revisions at this point. The situation is easy to detect because in an error state id will be -1.  I'm inclined to gracefully return the unprocessed object and handle it downstream. I still don't understand why catch() isn't catching the error.

Here's a possible change to postProcess:

```
const postProcess = function(data) {
  let pages = Object.keys(data.query.pages);
  
  let docs = pages.map(id => {      
    let page = data.query.pages[id] || {};
    if (id<0) 
    {
      // error condition. Return the error object
      return page;
    }
    let text = page.revisions[0]['*'];
    let options = {
      title: page.title,
      pageID: page.pageid,
    };
    return new Document(text, options);
  });
  //return an array if there was more than one page given
  if (docs.length > 1) {
    return docs;
  }
  //just return the first one
  return docs[0];
  
}
```

**Comment by simra** [comment]
Ok, now I see this was already fixed in the latest source. My package must have been out of date. I'll go ahead and close.

**Comment by simra** [comment]
I think I have the current version now. I submitted a new PR tonight to handle another error case, and add some tests.
