### ISSUE TITLE
Crash fetching Leonardo_da_Vinci

### ISSUE THREAD

**Issue by simra** [spencermountain/wtf_wikipedia#127]
Stack trace:
```
TypeError: data[k].text is not a function
    at Object.keys.forEach (.\node_modules\wtf_wikipedia\src\templates\misc.js:126:25)
    at Array.forEach (native)
    at Object.subject bar (.\node_modules\wtf_wikipedia\src\templates\misc.js:125:23)
    at doTemplate (.\node_modules\wtf_wikipedia\src\templates\index.js:35:31)
    at templates.top.forEach (.\node_modules\wtf_wikipedia\src\templates\index.js:69:12)
    at Array.forEach (native)
    at Object.allTemplates [as templates] (.\node_modules\wtf_wikipedia\src\templates\index.js:68:17)
    at doSection (.\node_modules\wtf_wikipedia\src\section\index.js:21:16)
    at Object.splitSections [as section] (.\node_modules\wtf_wikipedia\src\section\index.js:52:15)
    at main (.\node_modules\wtf_wikipedia\src\document\index.js:47:22)
```

**Comment by simra** [comment]
False alarm: I updated to latest and the issue is fixed.
That said, I encountered some issues that caused code parsing errors for Node. I'll submit a separate PR.
