### ISSUE TITLE
Example for fetching by page id in doc fails

### ISSUE THREAD

**Issue by ivanmkc** [spencermountain/wtf_wikipedia#140]
The example given in the doc is:

```
wtf.fetch(64646, 'de').then(console.log).catch(console.log)
```

This causes an exception as the regex in Line 12 of fetch.js expects a string.

```
/usr/local/bin/node routes/test.js
node_modules/wtf_wikipedia/src/fetch.js:25
  title = title.map(encodeURIComponent);
                ^

TypeError: title.map is not a function
    at makeUrl (node_modules/wtf_wikipedia/src/fetch.js:25:17)
    at getPage (node_modules/wtf_wikipedia/src/fetch.js:96:13)
    at Function.wtf.fetch (node_modules/wtf_wikipedia/src/index.js:10:10)
    at Object.<anonymous> (routes/test.js:3:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```

Changing the call to:
```
wtf.fetch('64646', 'de').then(console.log).catch(console.log)
```
leads to another exception:
```
(node:92027) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pages' of undefined
    at postProcess (node_modules/wtf_wikipedia/src/fetch.js:33:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:92027) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:92027) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Waiting for the debugger to disconnect...
```

**Comment by ivanmkc** [comment]
Looks good now!
