### ISSUE TITLE
TypeError: inlineParsers[name] is not a function

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#158]
Hi, some articles give this error on parsing:
```
TypeError: inlineParsers[name] is not a function
at doTemplate (/node_modules/wtf_wikipedia/src/templates/index.js:41:34)
at templates.top.forEach.tmpl (/node_modules/wtf_wikipedia/src/templates/index.js:92:12)
at Array.forEach (<anonymous>)
at Object.allTemplates [as templates] (/node_modules/wtf_wikipedia/src/templates/index.js:91:17)
at doSection (/node_modules/wtf_wikipedia/src/section/index.js:23:16)
at Object.splitSections [as section] (/node_modules/wtf_wikipedia/src/section/index.js:54:15)
at main (/node_modules/wtf_wikipedia/src/document/index.js:44:22)
at new Document (/node_modules/wtf_wikipedia/src/document/Document.js:22:15)
at pages.map.id (/node_modules/wtf_wikipedia/src/fetch.js:48:14)
at Array.map (<anonymous>)
at postProcess (/node_modules/wtf_wikipedia/src/fetch.js:37:20)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)
```
You can reproduce this by trying to parse article `Wallace Island Marine Provincial Park` or `Saint Clare's Hospital at Boonton Township`

**Comment by spencermountain** [comment]
hey thanks, nice one.
Got it fixed, should work now in `5.1.2`
cheers
