### ISSUE TITLE
subject bar commons section doesn't always parse nice

### ISSUE THREAD

**Issue by moustachedelait** [spencermountain/wtf_wikipedia#162]
If you request https://en.wikipedia.org/wiki/The_Tragedy_of_Hamlet,_Prince_of_Denmark

the subject bar wiki code looks like
`{{Subject bar
|portal1        = Shakespeare
|commons        = y
|q              = y
|s              = y
|s-search       = The Tragedy of Hamlet, Prince of Denmark
}}`
in src/templates/misc.js that will lead to this error:

TypeError: data[k].text is not a function
    at Object.keys.forEach (/Users/user/Dropbox/node/gr3/node_modules/wtf_wikipedia/src/templates/misc.js:127:23)
    at Array.forEach (<anonymous>)
    at Object.subject bar (/Users/user/Dropbox/node/gr3/node_modules/wtf_wikipedia/src/templates/misc.js:125:23)
    at doTemplate (/Users/user/Dropbox/node/gr3/node_modules/wtf_wikipedia/src/templates/index.js:35:31)
    at templates.top.forEach (/Users/user/Dropbox/node/gr3/node_modules/wtf_wikipedia/src/templates/index.js:69:12)
    at Array.forEach (<anonymous>)
    at Object.allTemplates [as templates] (/Users/user/Dropbox/node/gr3/node_modules/wtf_wikipedia/src/templates/index.js:68:17)
    at doSection (/Users/user/Dropbox/node/gr3/node_modules/wtf_wikipedia/src/section/index.js:21:16)
    at Object.splitSections [as section] (/Users/user/Dropbox/node/gr3/node_modules/wtf_wikipedia/src/section/index.js:52:15)
    at main (/Users/user/Dropbox/node/gr3/node_modules/wtf_wikipedia/src/document/index.js:47:22)

**Comment by spencermountain** [comment]
ah, rats. thanks Guido.
will check it out this weekend.

**Comment by spencermountain** [comment]
hey, this works [for me](https://runkit.com/spencermountain/5b918d5998d20a0012d0ecdc), 
which version are you on?
can you try it on the latest?

**Comment by moustachedelait** [comment]
4.2.0 
I'll have to try the latest.
Sorry to send you into the woods!

**Comment by spencermountain** [comment]
closing for now
