### ISSUE TITLE
Problem with parsing

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#235]
Hi, I've found few articles that fails to parse.
Articles: `Pitt Town, New South Wales`, `Schofields, New South Wales`, `Troy Hill (Pittsburgh)`
```
TypeError: Cannot read property 'length' of undefined
    at Object.historical populations (/app/node_modules/wtf_wikipedia/src/templates/politics/population.js:8:34)
    at parseTemplate (/app/node_modules/wtf_wikipedia/src/templates/parse.js:33:30)
    at templates.top.forEach.tmpl (/app/node_modules/wtf_wikipedia/src/templates/index.js:35:12)
    at Array.forEach (<anonymous>)
    at Object.parseTemplates [as templates] (/app/node_modules/wtf_wikipedia/src/templates/index.js:34:17)
    at oneSection (/app/node_modules/wtf_wikipedia/src/02-section/index.js:20:16)
    at Object.parseSections [as section] (/app/node_modules/wtf_wikipedia/src/02-section/index.js:71:13)
    at main (/app/node_modules/wtf_wikipedia/src/01-document/index.js:42:25)
    at wtf (/app/node_modules/wtf_wikipedia/src/index.js:9:10)
```

**Comment by spencermountain** [comment]
thanks, i'll take a look next week.
