### ISSUE TITLE
wtf-plugin-markdown:  Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by crystalfp** [spencermountain/wtf_wikipedia#341]
The example on the wtf-plugin-markdown npm module page:
```
const wtf = require('wtf_wikipedia');
wtf.extend(require('wtf-plugin-markdown'))
const doc = wtf('hello [[world]]')
const md = doc.markdown()
console.log(md);
```
crashes with the following error (under node v12.16.1, "wtf-plugin-markdown": "^0.1.0", "wtf_wikipedia": "^7.8.1") :
```
$ node .\wtf_wikipedia.js
D:\Projects\IdeaIgniterEnvironment\exp\node_modules\wtf-plugin-markdown\builds\wtf-plugin-markdown.js:420
    models.Link.prototype.markdown = _05Link;
                ^

TypeError: Cannot read property 'prototype' of undefined
    at plugin (D:\Projects\IdeaIgniterEnvironment\exp\node_modules\[4mwtf-plugin-markdown[24m\builds\wtf-plugin-markdown.js:420:17)
    at Function.wtf.extend (D:\Projects\IdeaIgniterEnvironment\exp\node_modules\[4mwtf_wikipedia[24m\src\index.js:31:3)
    at Object.<anonymous> (D:\Projects\IdeaIgniterEnvironment\exp\wtf_wikipedia.js:11:5)
[90m    at Module._compile (internal/modules/cjs/loader.js:1158:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:901:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m
[90m    at internal/main/run_main_module.js:18:47[39m
```
Thanks for looking!
mario

**Comment by spencermountain** [comment]
hey Mario, which version are you using? This plugin concept is new to v8
cheers

**Comment by crystalfp** [comment]
As I wrote, wtf_wikipedia version is 7.8.1 so I wait for version 8 published on nom.
Thanks!
