### ISSUE TITLE
Troubles with fr.wikipedia.org

### ISSUE THREAD

**Issue by zatteo** [spencermountain/wtf_wikipedia#36]
Hi,

I'm having troubles with the french wiki which returns me always {} with your example.

  wtf_wikipedia.from_api("Toronto", "en", function(markup){
    var obj= wtf_wikipedia.parse(markup);
    console.log(obj.infobox);
  })
-> works perfectly

  wtf_wikipedia.from_api("Toronto", "fr", function(markup){
    var obj= wtf_wikipedia.parse(markup);
    console.log(obj.infobox);
  })
-> return me {}

Any ideas ? Thanks for you work btw !

**Comment by spencermountain** [comment]
hi Théo!  thanks for the kind words.
I think this is fixed now, as of v4.0.0. can you check it out?
cheers!

**Comment by zatteo** [comment]
Ahah it's not working anymore for me and i don't know why, i'm getting this :

/home/zatteo/Projects/wtf_wikipedia2/node_modules/wtf_wikipedia/builds/wtf_wikipedia.js:28162
var xhr = new global.XMLHttpRequest()
          ^

TypeError: global.XMLHttpRequest is not a function
    at Object.<anonymous> (/home/zatteo/Projects/wtf_wikipedia2/node_modules/wtf_wikipedia/builds/wtf_wikipedia.js:28162:11)
    at Object.240 (/home/zatteo/Projects/wtf_wikipedia2/node_modules/wtf_wikipedia/builds/wtf_wikipedia.js:28195:4)
    at s (/home/zatteo/Projects/wtf_wikipedia2/node_modules/wtf_wikipedia/builds/wtf_wikipedia.js:2:627)
    at /home/zatteo/Projects/wtf_wikipedia2/node_modules/wtf_wikipedia/builds/wtf_wikipedia.js:2:678
    at Object.<anonymous> (/home/zatteo/Projects/wtf_wikipedia2/node_modules/wtf_wikipedia/builds/wtf_wikipedia.js:28198:18)
    at Object.241../capability (/home/zatteo/Projects/wtf_wikipedia2/node_modules/wtf_wikipedia/builds/wtf_wikipedia.js:28476:4)
    at s (/home/zatteo/Projects/wtf_wikipedia2/node_modules/wtf_wikipedia/builds/wtf_wikipedia.js:2:627)
    at /home/zatteo/Projects/wtf_wikipedia2/node_modules/wtf_wikipedia/builds/wtf_wikipedia.js:2:678
    at Object.<anonymous> (/home/zatteo/Projects/wtf_wikipedia2/node_modules/wtf_wikipedia/builds/wtf_wikipedia.js:28072:21)
    at Object.239../lib/request (/home/zatteo/Projects/wtf_wikipedia2/node_modules/wtf_wikipedia/builds/wtf_wikipedia.js:28151:4)

thanks !

**Comment by spencermountain** [comment]
yikes! thanks for the heads up.
i've been using browserify to package the builds, but it looks like it quietly transforms the 'request' into a client-side version without telling anyone. 
v0.4.3 just points to `src/index.js`, which isn't perfect either, but should work.

**Comment by zatteo** [comment]
it works ! thanks :)
