### ISSUE TITLE
Hard error on some queries

### ISSUE THREAD

**Issue by vorpalhex** [spencermountain/wtf_wikipedia#43]
Given a query of 'test' or 'blah', the following error with stack gets thrown:

```
TypeError: data.text.forEach is not a function
    at Object.plaintext (.../node_modules/wtf_wikipedia/src/index.js:198:15)
    at wtf.from_api (.../lib/commands/wiki.js:24:22)
    at Request._callback (.../node_modules/wtf_wikipedia/src/lib/fetch_text.js:28:7)
    at Request.self.callback (.../node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (.../node_modules/request/request.js:1060:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (.../node_modules/request/request.js:980:12)
```

Rolling back to `0.5.0` resolved this issue on the same queries so I'm assuming the issue came about in the latest update.

**Comment by spencermountain** [comment]
yikes,
thanks Derrick, i wasn't able to reproduce this but i went in and changed tons of stuff.... um so `npm update` and try it again?
i'll keep it open - tests are all passing..

**Comment by spencermountain** [comment]
hi derrick, this works for me, did you figure it out?
```js
const wtf = require('./src/index');
console.log(wtf.parse('blah'));
```
