### ISSUE TITLE
Can't handle https://en.wikipedia.org/wiki/Mick_Fuller

### ISSUE THREAD

**Issue by tmtmtmtm** [spencermountain/wtf_wikipedia#514]
Running 10.1.1 `wtf_wikipedia https://en.wikipedia.org/wiki/Mick_Fuller` completely fails:

```
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at Object.ship (file:///usr/local/lib/node_modules/wtf_wikipedia/src/template/custom/text-only/functions.js:661:69)
    at parseTemplate (file:///usr/local/lib/node_modules/wtf_wikipedia/src/template/parse/index.js:60:32)
    at parseNested (file:///usr/local/lib/node_modules/wtf_wikipedia/src/template/index.js:18:24)
    at file:///usr/local/lib/node_modules/wtf_wikipedia/src/template/index.js:40:28
    at Array.forEach (<anonymous>)
    at allTemplates (file:///usr/local/lib/node_modules/wtf_wikipedia/src/template/index.js:40:10)
    at process (file:///usr/local/lib/node_modules/wtf_wikipedia/src/template/index.js:51:24)
    at new Section (file:///usr/local/lib/node_modules/wtf_wikipedia/src/02-section/Section.js:59:5)
    at parseSections (file:///usr/local/lib/node_modules/wtf_wikipedia/src/02-section/index.js:69:19)
    at new Document (file:///usr/local/lib/node_modules/wtf_wikipedia/src/01-document/Document.js:80:22)
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at Object.ship (file:///usr/local/lib/node_modules/wtf_wikipedia/src/template/custom/text-only/functions.js:661:69)
    at parseTemplate (file:///usr/local/lib/node_modules/wtf_wikipedia/src/template/parse/index.js:60:32)
    at parseNested (file:///usr/local/lib/node_modules/wtf_wikipedia/src/template/index.js:18:24)
    at file:///usr/local/lib/node_modules/wtf_wikipedia/src/template/index.js:40:28
    at Array.forEach (<anonymous>)
    at allTemplates (file:///usr/local/lib/node_modules/wtf_wikipedia/src/template/index.js:40:10)
    at process (file:///usr/local/lib/node_modules/wtf_wikipedia/src/template/index.js:51:24)
    at new Section (file:///usr/local/lib/node_modules/wtf_wikipedia/src/02-section/Section.js:59:5)
    at parseSections (file:///usr/local/lib/node_modules/wtf_wikipedia/src/02-section/index.js:69:19)
    at new Document (file:///usr/local/lib/node_modules/wtf_wikipedia/src/01-document/Document.js:80:22)
file:///usr/local/lib/node_modules/wtf_wikipedia/cli.js:28
    console.log(JSON.stringify(doc[mode](), null, 0))
                                  ^

TypeError: Cannot read properties of null (reading 'json')
    at file:///usr/local/lib/node_modules/wtf_wikipedia/cli.js:28:35
    at file:///usr/local/lib/node_modules/wtf_wikipedia/src/_fetch/index.js:81:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.2.0
```

**Comment by spencermountain** [comment]
yikes! fixed in 10.1.2
thanks for the heads-up.
